# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84fba54e9531847bace0a280e695316d7bec0bdd7af761b832e2de3a1037f9522e9a912af73bd7cfc97ae7a69e6b8b05d16fc403a69d66767cba3df165170973

test:
  secret_key_base: 275ac3f9d721ce03480b5ce6d7106bf57a2e8568015f67cde8ec4e9594c9b9e8bee9d8873c6af57f58a8046be2f52415d3b29c4d6e1493d5b4e46b674671a890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
